/* Eksport polskiej karty PDF ładowany dopiero na żądanie. / Polish PDF export loaded only on demand. */
(function installAdvancedCreatorPdfExport(){
  'use strict';
  const PDF_LIB_URL='https://cdn.jsdelivr.net/npm/pdf-lib@1.17.1/dist/pdf-lib.min.js';
  const FONTKIT_URL='https://cdn.jsdelivr.net/npm/@pdf-lib/fontkit@1.1.1/dist/fontkit.umd.min.js';
  const FONT_URL='https://cdn.jsdelivr.net/gh/notofonts/noto-fonts@main/hinted/ttf/NotoSans/NotoSans-Regular.ttf';
  let dependenciesPromise=null;
  const byId=id=>document.getElementById(id);
  const loadScript=src=>new Promise((resolve,reject)=>{const existing=document.querySelector(`script[data-pdf-src="${src}"]`);if(existing){if(existing.dataset.loaded==='true')resolve();else existing.addEventListener('load',resolve,{once:true});return;}const script=document.createElement('script');script.src=src;script.async=true;script.dataset.pdfSrc=src;script.addEventListener('load',()=>{script.dataset.loaded='true';resolve();},{once:true});script.addEventListener('error',()=>reject(new Error(`Nie udało się załadować ${src}.`)),{once:true});document.head.appendChild(script);});
  async function ensureDependencies(){if(dependenciesPromise)return dependenciesPromise;dependenciesPromise=(async()=>{if(!window.PDFLib)await loadScript(PDF_LIB_URL);if(!window.fontkit)await loadScript(FONTKIT_URL);if(!window.PDFLib||!window.fontkit)throw new Error('Biblioteki PDF nie zostały załadowane.');})();try{return await dependenciesPromise;}catch(error){dependenciesPromise=null;throw error;}}
  const compact=text=>String(text||'').split('\n').map(line=>line.trim()).filter(Boolean).join(' / ');
  const pad2=value=>String(value).padStart(2,'0');
  const fileName=()=>{const d=new Date();return`PL-${d.getFullYear()}-${pad2(d.getMonth()+1)}-${pad2(d.getDate())}-${pad2(d.getHours())}${pad2(d.getMinutes())}.pdf`;};
  function setLog(message,error=false){const node=byId('pdfLogMessage');if(!node)return;node.textContent=message||'No PDF messages.';node.classList.toggle('is-error',error);}
  async function embedFont(pdfDoc){pdfDoc.registerFontkit(window.fontkit);const response=await fetch(FONT_URL);if(!response.ok)throw new Error('Nie udało się pobrać fontu Noto Sans.');return pdfDoc.embedFont(await response.arrayBuffer(),{subset:false});}
  function setText(form,name,value,font,warnings,skipBlank=true){const text=String(value??'');if(skipBlank&&!text.trim())return;try{const field=form.getTextField(name);field.setText(text);try{field.setFontSize(text.length>650?6:text.length>420?7:text.length>240?8:10);}catch(_){}try{field.updateAppearances(font);}catch(error){warnings.push(`Nie udało się ustawić fontu pola ${name}: ${error.message}`);}}catch(_){warnings.push(`Brak pola PDF: ${name}`);}}
  function setCheckbox(form,name,checked,warnings){try{const field=form.getCheckBox(name);checked?field.check():field.uncheck();field.updateAppearances();}catch(_){warnings.push(`Brak pola PDF: ${name}`);}}
  function removeTextField(form,name,font){try{const field=form.getTextField(name);try{field.setText('');field.updateAppearances(font);}catch(_){}try{form.removeField(field);}catch(_){}}catch(_){}}
  function wrap(text,font,size,width,prefix='- ',hanging='  '){const words=String(text||'').split(/\s+/).filter(Boolean),lines=[];let line=prefix;const measure=value=>font.widthOfTextAtSize(value,size);const flush=()=>{if(line.trim())lines.push(line);line=hanging;};for(const word of words){const candidate=line.trim()?`${line} ${word}`:`${line}${word}`;if(measure(candidate)<=width){line=candidate;continue;}if(line.trim())flush();if(measure(`${hanging}${word}`)<=width){line=`${hanging}${word}`;continue;}let chunk='';for(const char of word){if(chunk&&measure(`${hanging}${chunk}${char}`)>width){lines.push(`${hanging}${chunk}`);chunk=char;}else chunk+=char;}line=`${hanging}${chunk}`;}if(line.trim())lines.push(line);return lines;}
  function layout(entries,area,font){const normalized=entries.map(compact).filter(Boolean),gutter=10;for(let columns=area.minColumns;columns<=area.maxColumns;columns++){for(let size=area.maxFont;size>=area.minFont;size--){const colWidth=(area.width-gutter*(columns-1))/columns,lineHeight=size*1.18,perColumn=Math.floor(area.height/lineHeight),lines=normalized.flatMap(entry=>wrap(entry,font,size,colWidth));if(lines.length<=perColumn*columns)return{columns,size,colWidth,lineHeight,perColumn,lines,omitted:0};}}const columns=area.maxColumns,size=area.minFont,colWidth=(area.width-gutter*(columns-1))/columns,lineHeight=size*1.18,perColumn=Math.floor(area.height/lineHeight),all=normalized.flatMap(entry=>wrap(entry,font,size,colWidth)),capacity=perColumn*columns;return{columns,size,colWidth,lineHeight,perColumn,lines:all.slice(0,capacity),omitted:Math.max(0,all.length-capacity)};}
  function drawArea(pdfDoc,entries,area,font,warnings){if(!entries.length)return;const page=pdfDoc.getPages()[area.page];if(!page){warnings.push(`${area.label}: brak strony PDF.`);return;}const result=layout(entries,area,font),gutter=10,color=window.PDFLib.rgb(0,0,0);result.lines.forEach((line,index)=>{const column=Math.floor(index/result.perColumn),row=index%result.perColumn;page.drawText(line,{x:area.x+column*(result.colWidth+gutter),y:area.y+area.height-result.size-row*result.lineHeight,size:result.size,font,color});});if(result.omitted)warnings.push(`${area.label}: pominięto ${result.omitted} linii, ponieważ tekst nie mieści się w obszarze.`);}
  function buildEntries(data){const result={abilities:[],notes:[],background:[]};data.talents.forEach(talent=>{const entry=compact(talent.name);if(entry)result.abilities.push(entry);});data.rules.forEach(rule=>{const entry=compact(rule.name);if(!entry)return;if(rule.type==='backgroundBonus')result.background.push(entry);else if(rule.type==='archetypeAbility'&&rule.target==='none')result.abilities.push(entry);else result.notes.push(entry);});return result;}
  function fillStandard(form,data,font,warnings){const c=data.character,v=data.values;setText(form,'Poziom',c.gameTier,font,warnings,false);setText(form,'Gatunek',c.speciesName,font,warnings);setText(form,'Archetyp',c.archetypeName,font,warnings);setText(form,'Frakcja',c.factionName,font,warnings);setText(form,'Słowa Kluczowe',c.keywords,font,warnings);setText(form,'Rozmiar',c.size,font,warnings,false);setText(form,'Szybkość',v.speed,font,warnings,false);['S','Wt','Zr','I','SW','Int','Ogd'].forEach(key=>setText(form,key,data.attrs[key],font,warnings,false));window.WNGCreatorV2.SKILLS.forEach(skill=>{setText(form,skill.pdf,data.skills[skill.key],font,warnings,false);setText(form,skill.sum,data.skillTotals[skill.key],font,warnings,false);});[['Upór',v.resolve],['Odwaga',v.conviction],['Obrona',v.defence],['Bazowa Odporność',v.resilience],['Maksymalna Żywotność',v.woundsMax],['Odporność Psychiczna',v.shock],['Determinacja',v.determination],['Wpływy',v.influence],['Majątek',v.wealth],['Pasywna Czujność',v.passiveAwareness]].forEach(([name,value])=>setText(form,name,value,font,warnings,false));Array.from({length:25},(_,i)=>`Check Box ${i+1}`).forEach((name,index)=>setCheckbox(form,name,index<v.corruption,warnings));const levelMarks=Math.max(0,Math.min(4,Math.ceil((v.corruption-5)/5)));Array.from({length:5},(_,i)=>`Check Box ${i+26}`).forEach((name,index)=>setCheckbox(form,name,index<levelMarks,warnings));}
  function openPreview(){const preview=window.open('','_blank');if(preview){preview.document.write('<!doctype html><html><head><meta charset="utf-8"><title>Generowanie PDF…</title></head><body style="margin:24px;background:#000;color:#9cf09c;font-family:Consolas,monospace">Kantyk Maszyny przygotowuje podgląd PDF…</body></html>');preview.document.close();}return preview;}
  async function exportPdf(){const preview=openPreview(),warnings=[],button=byId('exportCharacterPdfButton');button.disabled=true;try{await ensureDependencies();const response=await fetch('./pdf/pl.pdf',{cache:'no-store'});if(!response.ok)throw new Error('Nie udało się pobrać ./pdf/pl.pdf.');const pdfDoc=await window.PDFLib.PDFDocument.load(await response.arrayBuffer()),font=await embedFont(pdfDoc),form=pdfDoc.getForm(),data=window.WNGCreatorV2.getComputedData(),entries=buildEntries(data);fillStandard(form,data,font,warnings);Array.from({length:8},(_,i)=>`Zdolności i talenty ${i+1}`).forEach(name=>removeTextField(form,name,font));removeTextField(form,'Notatki 1',font);removeTextField(form,'Przeszłość',font);drawArea(pdfDoc,entries.abilities,{page:1,x:40,y:578,width:530,height:118,minColumns:2,maxColumns:4,maxFont:10,minFont:5,label:'Zdolności i Talenty'},font,warnings);drawArea(pdfDoc,entries.notes,{page:1,x:25,y:40,width:410,height:135,minColumns:2,maxColumns:4,maxFont:10,minFont:5,label:'Notatki'},font,warnings);drawArea(pdfDoc,entries.background,{page:0,x:467,y:623,width:109,height:39,minColumns:1,maxColumns:3,maxFont:8,minFont:4,label:'Przeszłość'},font,warnings);const bytes=await pdfDoc.save({updateFieldAppearances:false}),blob=new Blob([bytes],{type:'application/pdf'}),url=URL.createObjectURL(blob),name=fileName();if(preview&&!preview.closed){preview.document.title=name;preview.location.replace(url);}else window.open(url,'_blank');setTimeout(()=>URL.revokeObjectURL(url),300000);setLog(warnings.length?warnings.join('\n'):'PDF został wygenerowany.');}catch(error){console.error('[TworzeniePostaci_v2 PDF]',error);setLog(error.stack||error.message,true);if(preview&&!preview.closed)preview.document.body.textContent=`Błąd generowania PDF: ${error.message||error}`;}finally{button.disabled=false;}}
  function initialize(){byId('exportCharacterPdfButton')?.addEventListener('click',exportPdf);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',initialize,{once:true});else initialize();
})();
